@echo off
cd /d "C:\laragon\www\SOTUMA"
echo Removing existing origin...
git remote remove origin
echo Adding new origin...
git remote add origin https://github.com/rokhsario/sotuma.git
echo Checking remote...
git remote -v
echo Pushing to GitHub...
git push --set-upstream origin main --force
echo Done!
pause
